// <auto-generated />
using System;
using ETL.API.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ETL.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ETL.API.DAL.Models.ETLData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DOLocationID")
                        .HasColumnType("int");

                    b.Property<float>("FareAmount")
                        .HasColumnType("real");

                    b.Property<int>("PULocationID")
                        .HasColumnType("int");

                    b.Property<int?>("PassengerCount")
                        .HasColumnType("int");

                    b.Property<string>("StoreAndFwdFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TipAmount")
                        .HasColumnType("real");

                    b.Property<DateTime>("TpepDropoffDatetime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TpepPickupDatetime")
                        .HasColumnType("datetime2");

                    b.Property<float>("TripDistance")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ETLData", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
